island_step "Post-install"
run_logged "$ISLAND_INSTALL/post-install/migrations.sh"

island_header
echo -e "\e[32m  Installation complete!\e[0m"
echo ""
echo "  Next steps:"
echo "  1. Log out of your current session"
echo "  2. Select 'Hyprland' from the session picker"
echo "  3. Log in"
echo ""
echo "  Quick start:"
echo "    SUPER+Return    Terminal (ghostty)"
echo "    SUPER+Space     App launcher (rofi)"
echo "    SUPER+B         Browser (firefox)"
echo "    SUPER+N         Network TUI (impala)"
echo ""
echo "  Full reference: $ISLAND_PATH/docs/keybindings.md"
echo ""
